export const assetContext = {
  totalAssets: 482,
  assetsInUse: 350,
  inRepair: 15,
  lowStockAlerts: 8,
  categories: {
    Electronics: 245,
    Furniture: 156,
    Software: 67,
    "Office Supplies": 14,
  },
  sampleAssets: [
    {
      id: "ASSET-00123",
      name: "16-inch MacBook Pro M3",
      category: "Electronics",
      status: "In Use",
      assignedTo: "Jane Doe",
      purchaseDate: "2024-01-15",
      warrantyEndDate: "2026-01-15",
      value: 2499.99,
      location: "Floor 7, West Wing",
    },
    {
      id: "ASSET-00124",
      name: "Herman Miller Chair",
      category: "Furniture",
      status: "In Storage",
      assignedTo: "Unassigned",
      purchaseDate: "2023-11-20",
      warrantyEndDate: "2028-11-20",
      value: 899.99,
      location: "Warehouse B",
    },
    {
      id: "ASSET-00125",
      name: 'Dell Monitor 27"',
      category: "Electronics",
      status: "In Repair",
      assignedTo: "John Smith",
      purchaseDate: "2023-08-10",
      warrantyEndDate: "2026-08-10",
      value: 349.99,
      location: "IT Department",
    },
    {
      id: "ASSET-00126",
      name: "Adobe Creative Suite",
      category: "Software",
      status: "In Use",
      assignedTo: "Design Team",
      purchaseDate: "2024-02-01",
      warrantyEndDate: "2025-02-01",
      value: 599.99,
      location: "Digital License",
    },
  ],
  recentActivity: [
    "3 assets added today",
    "2 status updates completed",
    "1 asset retired",
    "5 warranty renewals processed",
  ],
  upcomingWarranties: ["Adobe Creative Suite expires in 2 months", "3 laptops need warranty renewal next quarter"],
  note: "This file is deprecated - using live asset data from useAssetStore instead",
}
